# taken from: https://github.com/monoira/kitty-tabs/blob/main/tabs.conf

tab_bar_style separator
tab_separator ""
tab_bar_min_tabs 2

# Separators:
#                

tab_title_template "{fmt.fg._31313a}{fmt.bg._11111b}{fmt.fg._cdd6f4}{fmt.bg._31313a} ({index}) {title} {fmt.fg._31313a}{fmt.bg._11111b} "
active_tab_title_template "{fmt.fg._6D8086}{fmt.bg._11111b}{fmt.fg._1e1e2e}{fmt.bg._6D8086} ({index}) {title} {fmt.fg._6D8086}{fmt.bg._11111b} "
active_tab_font_style bold

map alt+& goto_tab 1
map alt+é goto_tab 2
map alt+" goto_tab 3
map alt+' goto_tab 4
map alt+( goto_tab 5
map alt+- goto_tab 6
map alt+è goto_tab 7
map alt+_ goto_tab 8
map alt+ç goto_tab 9

map ctrl+t new_tab
map ctrl+w close_tab

map ctrl+shift+page_up move_tab_backward
map ctrl+shift+page_down move_tab_forward

