[mgr]
ratio = [1, 3, 6]

[opener]
pdff = [
    { run = 'zen-browser "$@"', desc = "zen-browser", block = true, for = "unix"},
]

[open]
rules = [
    { mime = "application/pdf", use = [ "pdff", "reveal" ] },
]
